= Introducción
// // Dar una introducción al contexto del tema.
// // Explicar, en términos generales, el problema abordado.
// // Motivar la necesidad, la importancia y/o el valor, de tener una (mejor) solución.
// // En el caso de la práctica extendida, incluir detalles de la organización, su quehacer, el equipo y el supervisor con los cuales se va a trabajar, la relevancia del problema a la organización, etc.

En el vertiginoso panorama actual, caracterizado por la revolución digital y la saturación de datos e información, la seguridad de la información emerge como un baluarte fundamental para asegurar la continuidad y la confianza en las operaciones empresariales. En este contexto, la constante evolución de las amenazas cibernéticas y la creciente interconexión de sistemas han convertido la salvaguarda de la confidencialidad, integridad y disponibilidad de la información en una prioridad crítica, desafiando a las organizaciones a mantenerse a la vanguardia de la seguridad informática.

Las organizaciones, en este desafío constante, se ven compelidas a garantizar que sus sistemas no solo cumplan con los estándares de seguridad, sino que también sigan las mejores prácticas establecidas. Es en este contexto que el Sistema de Gestión de Seguridad de la Información (SGSI), especialmente dentro del marco de la norma ISO 27001, emerge como una guía esencial para diseñar, implementar y mantener sistemas de seguridad robustos. La certificación ISO 27001, por ende, no solo proporciona un marco sólido para la gestión de la seguridad de la información, sino que también otorga a las empresas un distintivo reconocido internacionalmente, validando su compromiso inquebrantable con la seguridad.

En el epicentro de este escenario complejo se halla la empresa Magnet, una entidad con una sólida trayectoria de más de una década en la provisión de soluciones tecnológicas a medida. Para Magnet, la necesidad imperante de asegurar la integridad y confidencialidad de su información y la de sus clientes, especialmente en el contexto de la certificación ISO 27001, adquiere una importancia estratégica. La creciente sofisticación de las amenazas cibernéticas y la diversificación de los vectores de ataque subrayan la relevancia y la urgencia de contar con un sistema de gestión de seguridad de la información robusto y certificado para proteger los activos digitales y salvaguardar la reputación de la empresa en el escenario empresarial actual.

No obstante, en medio de esta búsqueda de seguridad, las organizaciones enfrentan limitaciones al depender de soluciones externas para llevar a cabo la auditoría de cumplimiento. Es en este punto crítico que surge la motivación para el desarrollo de una solución interna y personalizada, impulsada por las tendencias actuales hacia la autonomía y la adaptabilidad en el dinámico panorama de la seguridad de la información. Las empresas, ahora más que nunca, buscan soluciones que no solo cumplan con los requisitos regulatorios, como la ISO 27001, sino que también ofrezcan flexibilidad y capacidad de adaptación a las cambiantes condiciones del entorno digital.

En respuesta a este desafío, el proyecto propuesto tiene como objetivo la creación de una "Plataforma para Auditoría de Cumplimiento del Sistema de Gestión de Seguridad de la Información", abordando de manera específica los desafíos que enfrenta Magnet y otras organizaciones en este ámbito crucial. Esta plataforma no solo aspira a cumplir con los requisitos de auditoría; se concibe como un habilitador estratégico que otorga a Magnet autonomía en la gestión de su certificación ISO 27001. Además, plantea la posibilidad de escalar y adaptar la solución para otras organizaciones con necesidades similares, contribuyendo así a la seguridad informática en un ámbito más amplio.

La solución propuesta adopta un enfoque integral al incorporar módulos especializados para la gestión eficiente de documentos, activos, riesgos y flujos asociados a los controles de ISO 27001. A través de tecnologías sólidas como Django, PostgreSQL y Typescript, se busca ofrecer no solo eficiencia operativa, sino también una base sólida para el desarrollo y la escalabilidad futura, asegurando que la plataforma evolucione al ritmo de las crecientes demandas de seguridad.

El plan de trabajo delineado abarca diversas fases, desde la preparación y planificación hasta la evaluación y refinamiento, garantizando un enfoque estructurado y metódico a lo largo de 15 semanas. Este cronograma no solo representa un compromiso con el proyecto, sino que también refleja la dedicación a alcanzar resultados tangibles en un plazo determinado.

En última instancia, este trabajo de título no se limita a resolver un problema específico de auditoría de cumplimiento del SGSI para Magnet; va más allá al buscar contribuir al panorama más amplio de la seguridad de la información. La plataforma propuesta no solo será una herramienta para alcanzar la certificación; será un activo estratégico que impulsa la seguridad, la adaptabilidad y la autonomía en un entorno empresarial digital en constante evolución. A medida que el proyecto avance, se espera que sus resultados no solo beneficien a Magnet, sino que también sirvan como un referente valioso para otras organizaciones que buscan fortalecer su postura en seguridad informática en un mundo cada vez más interconectado.